apiVersion: apps/v1
kind: Deployment
metadata:
  name: rusthello
  labels:
    app: rusthello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rusthello
  template:
    metadata:
      labels:
        app: rusthello
    spec:
      containers:
        - name: rusthello
          image: luzv/rust_hello
          ports:
          - containerPort: 8888

