apiVersion: v1
kind: Service
metadata:
  name: rusthello
  labels:
    app: rusthello
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8888
  selector:
    app: rusthello
  type: LoadBalancer

